DROP TABLE IF EXISTS noteful_notes;

CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    title TEXT NOT NULL, 
    content TEXT, 
    date_modified TIMESTAMPTZ NOT NULL DEFAULT now(), 
    folderId INTEGER REFERENCES noteful_folders(id) ON DELETE CASCADE NOT NULL
);